### ISSUE TITLE
unknown provider

### ISSUE THREAD

**Issue by alexdmejias** [BoLaMN/loopback-component-admin#11]
I just created a brand new project and added this module as a dependency. Created a user model called `player` and my component-config.json file looks like this:

```
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  },
  "loopback-component-admin": {
    "mountPath": "/admin",
    "userModel": "player"
  }
}
```

but when I launch the application and go to /admin, I get `angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: playerProvider <- player <- LoopBackAdminConfiguration`. Am I missing an installation step?

**Comment by BoLaMN** [comment]
This project uses the official loopback angular sdk to interface with the api server with a quick look at the function that builds the sdk it seems they forcefully uppercase every model name.

https://github.com/strongloop/loopback-sdk-angular/blob/master/lib/services.js#L78

Unfortunately there's nothing I can do with in the component to stop it, feel free to normalize to the uppercase variant or possibly submit a issue request with that module. 

Cheers

**Comment by alexdmejias** [comment]
@BoLaMN thanks! that seems to have fixed the unknown provider issue, but now I can't register. I removed the old player model and replaced with Player. Clicking on the register button does nothing, no errors in the console.

**Comment by BoLaMN** [comment]
the registration system was never completely finished as this project was ripped out of my main cms which I don't utilize the built in loopback user system so I removed the code that wasn't standard to loopback. 

it wouldn't be much work to implement it in the loopback way by modifying these two files to your needs 

https://github.com/BoLaMN/loopback-component-admin/blob/master/src/client/components/routing/register/register.controller.coffee 
https://github.com/BoLaMN/loopback-component-admin/blob/master/src/client/templates/routing/register.tpl.html

If you're just looking to create the first user to be able to login you're able to use 

https://github.com/BoLaMN/loopback-component-admin/blob/master/src/component/create-user.coffee 

as a boot script and change the user, password and email as needed, hope this gives some help.
