### ISSUE TITLE
Setting explicit custom API url on angular services

### ISSUE THREAD

**Issue by portokallidis** [BoLaMN/loopback-component-admin#3]
Hello, and congratz for the component

I have a problem , i am trying to get a loopback app running on c9.io
I cannot change the "host" param in config.json because it's not backwards discoverable, thus i am forced to config like this: "host":"0.0.0.0" in order for this to work.
The /admin component when i login tries to post to a non-existent url resulting to this:
angular.js:11209 POST http://0.0.0.0:8080/api/Users/login?include=user net::ERR_ADDRESS_INVALID

Is there an easy way of doing such thing?

**Comment by BoLaMN** [comment]
Hey, 

There wasn't anything implemented for it I've committed a change that'll enable you to define it as an option but I'll have to recompile it and republish it to make it public. 

Will try todo asap. 

https://github.com/BoLaMN/loopback-component-admin/commit/f5e5ffcf84aa7354a23e71cf78975582d14d61a7

**Comment by portokallidis** [comment]
Thanks for this! 
So in the component config there is an added option "url"?

```
 {
    "loopback-component-admin": {
      "mountPath": "/admin",
      "userModel": "CustomUserModelHere",
      "userLoginField": "email|username", 
      "url":"http://apiurl/api"
    }
 }
```

**Comment by BoLaMN** [comment]
Correct, once I'm able to recompile and push the new version to npm you sure be good to go. 

I'm just busy on another component atm, won't be long.

**Comment by portokallidis** [comment]
Great, dont rush it, i dont need it in any current project but i will definately use it in my next project.
It's a must addon for loopback

**Comment by BoLaMN** [comment]
I'll be adding two more components soon enough so I'm going to look at making the ui from this into more of a universal shell which you can enable the components you need for your ecosystem. 

Ones a node-red like component and the other is a identity management component for creating users, roles, client applications, scopes etc... which I've rewritten most of the built in auth models.

**Comment by sbehrends** [comment]
Any update on this?
Im having issues with http://undefined:3000 when pressing the login button.

**Comment by BoLaMN** [comment]
publish 0.0.7 to enable this.
