### ISSUE TITLE
When opening a model undefined order

### ISSUE THREAD

**Issue by sbehrends** [BoLaMN/loopback-component-admin#4]
Hello there,
I just installed the component, login worked great, and all models are properly listed. I can create a item in a model but can't get the list of the model items. In console I discovered that is not sending the filter properly.

Any idea?

```
{"include":[],"skip":0,"limit":15,"order":"undefined DESC"}
```

BTW: Do you have some more readme about how to customize the admin and other functions?

**Comment by BoLaMN** [comment]
Hey, 

not sure what could be added into a read me. 

Basically only 3 main things that everything is generated around, there's a few features that are implemented client side but I haven't released the server side components to go with them yet, like password change, avatar upload but I thought it might be handy for some one that's learning. 

Dashboard, Create/Edit and Table are defined by the property files and the column files in their respective folders.

I can add the instructions on how to use npm link and the grunt tasks for the dev env if that helps any?

Let me know what you're after or if I can shed light on anything else.

**Comment by sbehrends** [comment]
I would really appreciate more customization or personalization regarding models. Maybe what to show or hide. Would different roles show or hide models o to user? Customize login/register/social login links.
Add custom views?

**Comment by BoLaMN** [comment]
Interestingly enough I never really wanted to go as far as enabling customisation as I see it as more of an administrative tool similar to arc where if you wanted to have a highly customizatable ui one would wire up and use ng-admin. 

Customization is not totally out of the question thou as when it creates the config.json from the models it includes anything that's defined within the model denifition which could be use to enable ui customisation.

The social links are a left over from my main project which this was derived from where the social links are written in the database per client application. 

I'm currently working towards open sourcing it.

These links could be easily moved to a dynamic setting similar to the optional userOrEmail field setting in the component-config.json if needed. 

Cheers
