### ISSUE TITLE
JSON only parameters

### ISSUE THREAD

**Issue by MarkAndrewJohnson** [BoLaMN/loopback-component-admin#6]
This component only works with JSON filter parameters, not traditional style parameters (ie filter[where][foo]=bar).  The following code breaks, and should probably only parse as JSON if args is a string and not already an object.

On line 27:
`filter = JSON.parse(ctx.args.filter).where;`

**Comment by BoLaMN** [comment]
Can wrap a try/catch around it to facilitate both instances maybe? 

filter = ctx.args.filter

try
  filter = JSON.parse ctx.args.filter
catch e

might do the trick?
