### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by Industrial** [BoLaMN/loopback-component-admin#9]
Hi.

I have a user model called `user`.

My error is: `Error: [$injector:unpr] Unknown provider: userProvider <- user <- LoopBackAdminConfiguration
http://errors.angularjs.org/1.5.0-rc.0/$injector/unpr?p0=userProvider%20%3C-%20user%20%3C-%20LoopBackAdminConfiguration`

**Comment by BoLaMN** [comment]
See #11 for issue, seems to be the official sdks doing. 

Cheers
